### ISSUE TITLE
Pipeline does not run anymore

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/ontotools-docker#15]
Unfortunately some server related issues seem to prevent the pipeline from running:

https://github.com/monarch-initiative/ontotools-docker/actions/runs/7685176210/job/20942540707

@twhetzel can you take this on?

**Comment by twhetzel** [comment]
I checked the logs listed in the error message from the GH Action. 
```
-rw-r--r-- 1 ols_deployer ols_deployers     0 Jan 28 10:41 deploy_20240128_104130_stderr.log
-rw-r--r-- 1 ols_deployer ols_deployers 26219 Jan 28 10:45 deploy_20240128_104130_stdout.log
```

While the stderr file is empty, the error is in the stdout file:
```
Traceback (most recent call last):
  File "/work/github/main/vertebrate-breed-ontology/src/ontology/../scripts/find_dadis_transboundary_ids.py", line 231, in <module>
    raise ValueError("DADIS API key not set. Set the DADIS_API_KEY environment variable or use the --dadis_api_key argument")
ValueError: DADIS API key not set. Set the DADIS_API_KEY environment variable or use the --dadis_api_key argument
make[1]: *** [vbo.Makefile:78: components/dadistransbound.tsv] Error 1
make[1]: Leaving directory '/work/github/main/vertebrate-breed-ontology/src/ontology'
make: *** [Makefile:47: ontologies/vbo-edit.owl] Error 2
```

I don't know what an `DADIS API key` is. @falquaddoomi do you know, could this have broken when the GCP account details were updated by Kevin recently?

**Comment by matentzn** [comment]
Greeeaaat thanks @twhetzel I know what it is. wow.. speaking of _bowels_... (its a pipeline step in VBO).

**Comment by matentzn** [comment]
Hopefully this fixes the problem: https://github.com/monarch-initiative/vertebrate-breed-ontology/commit/56bbd95485fcc92e4e9aa87b5468fddfb81e70b3

Thanks a ton @twhetzel for the diagnosis!

**Comment by twhetzel** [comment]
Thanks for the link to the update. I only saw the typo fix here in this repo so I didn't realize this was specific to VBO. Fingers crossed it's ok now...

**Comment by twhetzel** [comment]
That worked! Monarch OLS is back up and VBO fix visible.
