### ISSUE TITLE
redeploy.sh appears to be broken

### ISSUE THREAD

**Issue by falquaddoomi** [monarch-initiative/ontotools-docker#6]
Since the introduction of the `hp-branch-lymphoma` ontology in commit 3bc4620012ae46f442d0eeef17b4718e337390f8, the [redeploy.sh](https://github.com/monarch-initiative/ontotools-docker/blob/master/redeploy.sh) script has been failing. Specifically, the process started https://github.com/monarch-initiative/ontotools-docker/blob/master/redeploy.sh#L126 fails with the following output:

```
INFO: OXO - Extract mappings... (2107 sec)
Reading datasources from OxO...
querying http://oxo-web:8080/api/datasources?size=4000
Reading datasources from OxO done
http://ols-solr:8983/solr/ontology/select?q=%2A%3A%2A&fq=ontology_name%3Aefo&rows=0&wt=csv
<http.client.HTTPResponse object at 0x7f6e017bd220>
Done processing EFO, starting to query OLS
Traceback (most recent call last):
  File "/opt/oxo-loader/OlsMappingExtractor.py", line 254, in <module>
    processSolrDocs(olsDbxrefSolrQuery)
  File "/opt/oxo-loader/OlsMappingExtractor.py", line 218, in processSolrDocs
    scope = OXO.getScopeFromOls(fromCurie, fromOntology, toCurie)
  File "/opt/oxo-loader/OxoClient.py", line 187, in getScopeFromOls
    reply = urllib.request.urlopen(olsurl)
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Random guesses at solutions:
- One possible suspect is the `sleep` statements, e.g., https://github.com/monarch-initiative/ontotools-docker/blob/master/redeploy.sh#L103; perhaps they aren't long enough for the databases to become fully populated.
- It's also possible that the `efo` ontology referenced in the link that throws the 404, `http://ols-solr:8983/solr/ontology/select?q=*:*&fq=ontology_name:efo&rows=0&wt=csv`, simply isn't being loaded.

**Comment by twhetzel** [comment]
FWIW, in the Monarch instance of OLS the ontology EFO is not loaded. I have not yet looked at what `/opt/oxo-loader/OlsMappingExtractor.py` is doing. I am also a little puzzled why this error is happening after adding another ontology (hp-branch-lymphoma) into Monarch OLS.

**Comment by falquaddoomi** [comment]
Ah, sorry, I misread the log. It appears that it is getting past that part that references EFO, evidenced by the fact that it outputs "Done processing EFO, starting to query OLS", but there's a later request that throws a 404 where the URL is unfortunately not getting logged. I presume it's occurring in oxo-loader here: https://github.com/EBISPOT/OXO/blob/dev/oxo-loader/OlsMappingExtractor.py#L257-L258.

I should also mention that I'm not sure that it's the introduction of a new ontology that's causing this problem, only that I noticed the problem occurring after that commit.

**Comment by matentzn** [comment]
This does not ring a bell, and since we are talking about docker images here, it seems hard to imagine that this could have caused a problem.

Random possibility: the oxo loader was dependent on _ols_ life API, which recently changed (in some ways broke).

the ontotools suite is deployed in their entirety here. You can ask @udp if he can tell you in 1 second wether you can add a parameter to the docker compose file (or oxo-config.ini) that can ensure that no attempt is made at accessing EBI OLS, otherwise I would simply recommend to remove oxo from the docker compose file.

Do not spend time hacking any docker files - we need to move to OLS 4 asap!

**Comment by twhetzel** [comment]
If Nico does not have a requirement that OxO be deployed, then yes let's remove OxO.

**Comment by matentzn** [comment]
@falquaddoomi let me know if this solves your issue!

**Comment by twhetzel** [comment]
This was fixed with [Hotfix: added SKIP_OXO flag to skip loading and starting OXO containers](https://github.com/monarch-initiative/ontotools-docker/commit/231277e73527e92a4d42e7e6a22647749d0162f9) so closing. Thanks @falquaddoomi!
